### ISSUE TITLE
Add option to pass a `handleSummary` file

### ISSUE THREAD

**Issue by mbolotov** [k6io/k6#1946]
An option for passing a dedicated JS file with a `handleSummary()` function implementation is nice to have. 
It will allow customizing output from CLI that is required for threshold reporting within k6 IntelliJ plugin, see [here](https://github.com/k6io/intellij-plugin/issues/3)

**Comment by na--** [comment]
If I understand your use case, then we don't need to make a k6 change for this, you can do it even now. It probably can be done with ES6 [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and [`export`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export), but here's an ES5.1 solution that would work even with [`--compatibility-mode=base`](https://k6.io/docs/using-k6/javascript-compatibility-mode).

If the user's script is called `script.js` and contains:
```js
import { sleep } from "k6";
import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';


export function handleSummary(data) {
    console.log('script.js handleSummary()');

    return {
        'stdout': textSummary(data, { indent: ' ', enableColors: true, }),
    };
}

export default function () {
    console.log('script.js main');
    sleep(1);
}
```

simply have your IntelliJ plugin execute `k6 run wrapper.js` where `wrapper.js` contains something like this:
```js
var script = require('./script.js');

function wrapperHandleSummary(data) {
    console.log('wrapper.js handleSummary()');
    var result = script.handleSummary ? script.handleSummary(data) : {};
    result['/tmp/path-to-results-for-your-extension.json'] = JSON.stringify(data);
    return result;
}

Object.assign(exports, script, { handleSummary: wrapperHandleSummary });
```

I'll close this, since I doubt we'll ever implement a CLI flag for `handleSummary` without a significantly stronger use case, but please comment if you think my proposed solution isn't suitable or if you disagree in some other way and I'll reopen the issue.
