### ISSUE TITLE
Unable to install k6 from rpm

### ISSUE THREAD

**Issue by isandratskiy-ledger** [k6io/k6#1989]
Used commands:
`wget https://bintray.com/loadimpact/rpm/rpm -O bintray-loadimpact-rpm.repo
  sudo mv bintray-loadimpact-rpm.repo /etc/yum.repos.d/
  sudo yum -y install k6`
  
  Log output:
  
  
```
 2021-04-27 13:19:20--  https://bintray.com/loadimpact/rpm/rpm
Resolving bintray.com (bintray.com)... 75.126.118.184
Connecting to bintray.com (bintray.com)|75.126.118.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'bintray-loadimpact-rpm.repo'

     0K                                                        19.0M=0s

2021-04-27 13:19:21 (19.0 MB/s) - 'bintray-loadimpact-rpm.repo' saved [191]

Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package k6.x86_64 0:0.31.1-2.changerepo will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package
        Arch       Version                    Repository                   Size
================================================================================
Installing:
 k6     x86_64     0.31.1-2.changerepo        bintray--loadimpact-rpm     6.8 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 6.8 k
Installed size: 0  
Downloading packages:
Running transaction check
RPM needs to be updated
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by k6-0.31.1-2.changerepo.x86_64
```

**Comment by na--** [comment]
Where did you read the old installation instructions? We're [moving out of bintray](https://k6.io/blog/sunsetting-bintray/), because [they're shutting down the service](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), and we've updated all of our installation instructions ([1](https://k6.io/docs/getting-started/installation/), [2](https://github.com/k6io/k6#linux)) to the new [dl.k6.io](https://dl.k6.io/) repositories... Did we miss something?

Also, what Linux distribution are you using? I'm asking out of curiosity, it doesn't really matter, because the `0.31.1-2.changerepo` package would have returned an intentional error even if your distro could handle zstd packages. That was its point, it's a bogus package that has a preinstallation script that exits with a non-zero code after printing this:
>The repo you are using for installing k6 is being shut down as a result of Bintray sunsetting its service on May 1st 2021.
> The k6 team has created a new package repository where future packages will be published.
> In order to upgrade we recommend that you follow the new installation instructions at https://k6.io/docs/getting-started/installation/ and remove the Bintray repository and key as mentioned in the "Note about Bintray" section.

Anyway, I just uploaded an `0.31.1-3.changerepo` package version that has the same warning but should also work on non-zstd systems.

**Comment by isandratskiy-ledger** [comment]
@na--  using cent os
moved now to 
```
sudo yum -y install https://dl.k6.io/rpm/repo.rpm
sudo yum -y install k6
  ```
  but still have 
  ```
  Installing:
 k6     x86_64     0.31.1-2.changerepo        bintray--loadimpact-rpm     6.8 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 6.8 k
Installed size: 0  
Downloading packages:
Running transaction check
RPM needs to be updated
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by k6-0.31.1-2.changerepo.x86_64
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2021-04-27.14-22.xYBWJk.yumtx
 ```

**Comment by na--** [comment]
Did you follow the instructions from the "⚠️ Note about Bintray" section in the [installation docs](https://k6.io/docs/getting-started/installation/), to remove the old bintray rpm repo? If so, and it still doesn't work, you might want to run `yum clean metadata` or `yum clean all` to clear your yum cache... :man_shrugging:

**Comment by isandratskiy-ledger** [comment]
failed cos `sudo yum install https://dl.k6.io/rpm/repo.rpm` throw `Error: Nothing to do`
doing this in try https://github.com/LedgerHQ/k6-install-action/blob/master/index.js#L7 lol )))
and skip error on selfhosted when installed already.
