### ISSUE TITLE
Question: Using the this keyword (referring to a class context) inside k6 groups

### ISSUE THREAD

**Issue by filfreire** [k6io/k6#2001]
## The problem

> TL;DR: I have trouble using JS's `this` keyword inside a k6 `group`, for example, if the `group` is set inside a method of a JS `class`, of which we are trying to reference with `this.`.

> Note: I'm using `k6 v0.31.1 (2021-04-29T08:11:48+0000/af1e032, go1.16.3, linux/amd64)` through docker `Docker version 20.10.5, build 55c4c88`

Let's say I have a k6 script that defines some `groups`, within these groups I instance an object of a class:
```
import {group} from 'k6';
import { ExampleClass } from './util/exampleclass.js';

export default function() {
  group('example flow using example class', function () {
    let arg = //some argument we get via ENV or config, ...
    let dummy = new ExampleClass(arg);
    dummy.create_account();
  });
}
```

The `ExampleClass` is defined as:
```
import http from 'k6/http';
import { group, check } from 'k6';


export class ExampleClass {
    constructor(arg) {
        // we initialize some args, e.g.
        this.someHeaders = ...
        this.newAccount = ...
        // ...
    }
    create_account() {
        let url = // some url
        group('create an account' function (){
            var r = http.post(url, this.newAccount, {headers: this.someHeaders});
            // do some checks on r
        });
}
```

As of now (`k6 v0.31.1`), if the user tries to refer to `this` keyword (as in, trying to refer to context of the class), we'll get an error similar to:

```
"TypeError: Cannot read property 'newAccount' of undefined\n\tat file:///util/exampleclass.js:29:50(7)\n\tat github.com/loadimpact/k6/js/common.Bind.func1 (native)\n\tat create_account (file:///util/exampleclass.js:27:27(12))\n\tat file:///-:16:25(11)\n\tat github.com/loadimpact/k6/js/common.Bind.func1 (native)\n\tat file:///-:13:17(5)\n" executor=shared-iterations scenario=default source=stacktrace
```

I'm not sure if this is by design/intended or something of how JS works, so my **questions** are:
- Is this expected/intended?
- Is there any way we can refer to the class's context inside a k6 `group` defined within a method of that class?

### Current workaround

A workaround I'm using in order to be able to access the class's context within the k6 `group` has been to save `this` into a var:

```
create_account() {
    let url = // some url
    let t = this;
    group('create an account' function (){
        var r = http.post(url, t.newAccount, {headers: t.someHeaders});
```
﻿

**Comment by imiric** [comment]
Hi there! In general these types of questions are better suited for our [community forum](https://community.k6.io/). Please read [SUPPORT.md](https://github.com/k6io/k6/blob/master/SUPPORT.md). I'm not a JS expert, but I'll attempt to answer this here anyway.

The behavior of `this` is a common gotcha in JavaScript, but in this case I think goja, the JS VM k6 uses, is behaving correctly.

First of all note that k6 compiles JS files in strict mode, see #914. This has several implications, but it affects the behavior of `this` so that it returns `undefined` when used inside of a function. See the [examples on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#securing_javascript).

One workaround is to store the reference to `this` within the class context as you've done and use that inside the function, which is perfectly acceptable IMO.

Another perhaps more canonical workaround would be to use arrow functions [which do retain the value of the enclosing context's `this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#arrow_functions).

So in your case you would have:

```javascript
create_account() {
    let url = // some url
    group('create an account', () => {
        var r = http.post(url, this.newAccount, {headers: this.someHeaders});
    });
}
```

Hope this helps :)
