### ISSUE TITLE
Nomenclature for verbose logging 

### ISSUE THREAD

**Issue by vishalkuo** [k6io/k6#2004]
## Feature Description

`k6` has two different ways to configure logging: using `-v/--verbose` which is general "debug" logging by the k6 binary and `--http-debug` which provides debug information about http requests. 

While debugging an issue, I came across [this error message](https://github.com/k6io/k6/blob/af1e032ebf949cde092d4a2eddb78528ea0a5864/output/statsd/output.go#L175) and was briefly confused. `--http-debug` is the first option I reached for (based on a google query) and I had to read the docs more carefully to come across `--verbose` (I know it's listed [here](https://k6.io/docs/cloud/analyzing-results/logs/) but I think I actually resorted to reading the source code).

![image](https://user-images.githubusercontent.com/7549938/117081110-1341a900-acf4-11eb-835f-91d683459e86.png)
  

## Suggested Solution (optional)

I think the simplest solution is to have that error message suggest to use `--verbose` as a flag, instead. I briefly looked for other references to turning on `debug logging` and couldn't find any, so I think this is the only place. A longer term solution might be renaming `--verbose` to `--binary-debug` or `--developer-debug` to be more in-line with `--http-debug`. Possibly warrants more discussion. 

I'm going to open a PR for part 1 since I think it's more uncontroversial and a small enough change that I don't mind if it gets rejected / changed up

**Comment by imiric** [comment]
Hi, thanks for opening this issue and for the PR, and apologies for the confusion.

You're right, I can see how that would be confusing, especially since `--verbose` is not documented on the [Options page](https://k6.io/docs/using-k6/options/), which is also the case for other global CLI flags like `--quiet` and `--no-color`.

The "debug logging" nomenclature is used in the output of `k6 --help` however:
https://github.com/k6io/k6/blob/af1e032ebf949cde092d4a2eddb78528ea0a5864/cmd/root.go#L235

So we should probably change that to `Enable verbose logging` instead as well.

> A longer term solution might be renaming `--verbose` to `--binary-debug` or `--developer-debug` to be more in-line with `--http-debug`.

Instinctively I disagree with this as `--verbose` is a commonly used flag in CLI tools and we shouldn't deviate from that. I see a small case for renaming `--http-debug` to `--http-verbose` or `--verbose-http` to be consistent, but given this is an old and commonly used flag, we probably shouldn't break compatibility for the sake of this minor consistency.

The change in your PR looks good to me, but I'll refrain from merging it just yet since we have a release scheduled for next week, and we're pretty much in code freeze right now. Most of the k6 core team is on vacation, but we'll get back to you sometime next week, and probably merge your PR since it's a harmless change.

**Comment by vishalkuo** [comment]
> So we should probably change that to Enable verbose logging instead as well.

Awesome, make sense. Would you like me to change that in this PR or a subsequent one 

> Instinctively I disagree with this as --verbose is a commonly used flag in CLI tools and we shouldn't deviate from that. I see a small case for renaming --http-debug to --http-verbose or --verbose-http to be consistent, but given this is an old and commonly used flag, we probably shouldn't break compatibility for the sake of this minor consistency.

Makes sense. I don't feel strongly about `http-verbose` so I'm fine to maintain the status quo

> The change in your PR looks good to me, but I'll refrain from merging it just yet since we have a release scheduled for next week, and we're pretty much in code freeze right now. Most of the k6 core team is on vacation, but we'll get back to you sometime next week, and probably merge your PR since it's a harmless change.

Awesome, thanks. I'll follow up post release sometime next week if I don't hear back, thanks.

**Comment by imiric** [comment]
> Would you like me to change that in this PR or a subsequent one

The same PR would be fine, just a separate commit, but we'll get back to you once we have consensus on the team.

**Comment by vishalkuo** [comment]
Sure, I'll wait for that then.

**Comment by na--** [comment]
https://github.com/k6io/k6/pull/2005 is a good change and :+1: for `Enable verbose logging instead as well` in the CLI `--verbose` help text, but I agree with this sentiment regarding the test:
> given this is an old and commonly used flag, we probably shouldn't break compatibility for the sake of this minor consistency.

**Comment by vishalkuo** [comment]
Thanks! I've updated the PR. Please let me know if anything else is required

**Comment by MStoykov** [comment]
fixed by https://github.com/k6io/k6/pull/2005
