### ISSUE TITLE
No File/Directory while running the bundle.js test script from docker 

### ISSUE THREAD

**Issue by ash8454** [k6io/k6#2011]
Hello, 

I am having problem while running bundle.js test script with docker. I am able to run the bundle script just fine without using docker command. 

Below is the docker command.
`
docker run -v /Users/ash4141/k6/dist:/dist -i loadimpact/k6 run - <dist/test.bundle.js -e MY_HOSTNAME=127.0.0.1 -e ROOT_USERNAME=test -e ROOT_PASSWORD=test
`
I get the following error.
`no such file or directory at github.com/loadimpact/k6/js/common.Bind.func1 (native)"`

**Comment by na--** [comment]
What does `bundle.js` contain? Because this error suggests it's trying to `open()` a file that doesn't exist or isn't mounted properly in the docker container or something like that. It doesn't seem like a bug in k6, so I suggest you ask for help in the community forum if you can't diagnose the issue yourself: https://community.k6.io/
