### ISSUE TITLE
panic when importing modules from cdnjs

### ISSUE THREAD

**Issue by na--** [k6io/k6#2037]
From https://community.k6.io/t/out-of-the-blue-k6-is-throwing-panic/1762

This script causes a panic:
```js
import faker from "cdnjs.com/libraries/Faker";

export default function () {
}
```

**Comment by MStoykov** [comment]
relevant upstream issue `https://github.com/Marak/faker.js/issues/1173`.

The problem is that cdnjs tells us there is version 5.X.X but that version has no files defined for it and when we try to get the first one we panic (the array of files is empty).
Given the current issue there are 2 fixes:
1. when we can't find the file (the place where it breaks) because there are no files for the latest version - just abort ...
2. order versions and get the latest oldest version.

`1.` will be super simple, `2.` will take some work and will be hard to test. Given that I have been for dropping cdnjs (and github to some extend) magical links since 2 years ago when I *fixed* them for archives .... I am more inclined for `1.` and a big warning that people should just use real URLs.

**Comment by na--** [comment]
I also vote for 1. - this is an error, we should treat it as such, we should just not panic when it happens.

Also, I vote we should deprecate the cdnjs magic loading... In k6 v0.33.0, we should emit a warning somewhat like this:
```
Importing libraries from cdnjs.com without a scheme is deprecated, instead of "cdnjs.com/libraries/moment.js/2.18.1" import it like "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"
```

**Comment by na--** [comment]
We had a side-channel discussion of this and the decision was that we won't deprecate any of the "magic" loaders quite yet. The reasons for that are:
- All of the hard work for supporting them has already been done and is mostly stable
- We'd have to support .tar bundles with such scripts for quite a while yet anyway
- The functionality (or something like it) might actually be more useful in the future, potentially in conjunction with xk6 extensions
