### ISSUE TITLE
Add Custom metrics getName() method

### ISSUE THREAD

**Issue by david-gourde** [k6io/k6#2053]
## Feature Description

Currently, the custom metrics objects (like Counter) cannot return its own name.

It can be very useful to have it though. The reason is that I keep track of metrics in Go extensions as well, and return all of them in a map. I need to know the metric’s name to know which goes with which.

## Suggested Solution (optional)

Adding a `getName()` method to each [Metric types](https://k6.io/docs/using-k6/metrics/#metric-types). Note: They currently only have one method each, which is `add(<value>)`, but they each have the `name` parameter set in their constructor.

**Comment by na--** [comment]
@olimpias and @david-gourde, we decided that instead of a `getName()` method, we'd like to use a simple read-only `name` property in every `Metric` object, see https://github.com/k6io/k6/pull/2076. 

The read-only property seems like a more idiomatic approach to get this information JavaScript... :man_shrugging: Thank you again for the idea and the effort, we probably wouldn't have done it without you and we're still crediting you in the release notes (https://github.com/k6io/k6/pull/2077)! :bow:
