### ISSUE TITLE
Provide decent stack traces in setup code

### ISSUE THREAD

**Issue by neerolyte** [k6io/k6#994]
When an Error is thrown in setup it'd be nice if an exception was thrown, currently we just get the current function, file and line (which often seems to be wrong?). E.g:

```
$ cat foo.js
import bar from "./bar.js";
export function setup() {
        bar();
};
export default function() {
};
$ cat bar.js 
export default function () {
        baz();
}
function baz() {
        throw new Error("baz");
}
$ docker run -it --rm -v "$PWD:/src" -w /src loadimpact/k6 run foo.js

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: foo.js

    duration: -,  iterations: 1
         vus: 1, max: 1

ERRO[0000] Engine error                                  error="setup: Error: baz at baz (/src/bar.js:6:8(4))"
ERRO[0000] Engine Error 
```

**Comment by cuonglm** [comment]
This seems to be the same underlying issue with https://github.com/loadimpact/k6/issues/702.

> currently we just get the current function, file and line (which often seems to be wrong?)

The error message is display, `baz at baz` comes from `throw new Error("baz");`.

**Comment by MStoykov** [comment]
The good stacktrace is now produced by this lines https://github.com/loadimpact/k6/blob/8f4797d2761560fefb3e01c1bf440ee6a1c55548/lib/executor/helpers.go#L98-L107 Which basically check "badly" that something is goja.Exception.

I would argue that so that we don't get goja in `lib/...` even more we have another error type that the runner wrap ~errors~ exceptions in before returning them as otherwise we just hope that whatever we get and has String is actually goja.Exception ... https://github.com/dop251/goja/blob/e21ccf39bfce/runtime.go#L301
